### ISSUE TITLE
Alarm doesn't go off after 24 hours

### ISSUE THREAD

**Issue by giamby3000** [SheldonNeilson/Android-Alarm-Clock#7]
I have a question about your service: I noticed that alarms go off at once then after 24hours thet don't go off at all, if my phone isn't turn off.
any iideas?
This behaviour occurs with Android 4.2,2
I tried to add some instructions at your service destroy method:

public void onDestroy() {

super.onDestroy();
startService(new Intent(this, YourService.class));

}

because I thought that it was Android that kill your service, but the problem isn't fix

Thanks

**Comment by SheldonNeilson** [comment]
Hi. Does this happen if you use the code exactly as is is here? I've tried this on multiple Android versions including lollipop and it works fine...

**Comment by giamby3000** [comment]
Hi. 
Actually I modified your project: I can select if turn off or turn on Bluetooth when alarm goes off and I can open an app when set alarm goes off. But after 24 / 48 hours service doesn't start. 
If you want I can send you your modified project.

thanks

**Comment by SheldonNeilson** [comment]
I'll mail you privately to give you my email address.

**Comment by SheldonNeilson** [comment]
Hi

 

I’ll have a look at your project if you like.

 

S

**Comment by giamby3000** [comment]
Thank you very much .
Please give me a repository in order to send the project. It is 3MB large. 
Thank you
